stages:
  data_download:
    cmd: python src/stages/stage_0_data_download.py --config=params.yaml
    deps:
      - src/stages/stage_0_data_download.py
      - params.yaml
    params:
      - paths.dataset_url
      - paths.raw_dataset_dir
      - paths.dataset_path
    outs:
      - dataset/raw
    always_changed: false

  data_preprocess_augmentation:
    cmd: python src/stages/stage_1_data_preprocess_augmentation.py --config=params.yaml
    deps:
      - src/stages/stage_1_data_preprocess_augmentation.py
    params:
      - paths.preprocess_dataset
      - paths.train_dir
      - paths.labels_dir
    outs:
      - dataset/preprocess/train
      - dataset/preprocess/test

  train:
    cmd: python src/stages/stage_2_train.py --config=params.yaml
    deps:
      - src/stages/stage_2_train.py
    params:
      - paths.preprocessed_train
      - paths.preprocessed_val
      - paths.trained_model_path
    outs:
      - models/lenet.keras
      - models/mini_vgg_net.keras
      - models/shallownet.keras

  evaluate:
    cmd: python src/stages/stage_3_evaluate.py --config=params.yaml
    deps:
      - src/stages/stage_3_evaluate.py
    params:
      - paths.trained_model_path
      - evaluate.reports_dir
    outs:
      - src/reports/results