stages:
  data_download:
    cmd: python src/stages/stage_0_data_download.py --config=params.yaml
    deps:
    - src/stages/stage_0_data_download.py
    outs:
    - dataset/raw
  data_preprocess_augmentation:
    cmd: python src/stages/stage_1_data_preprocess_augmentation.py --config=params.yaml
    deps:
    - src/stages/stage_1_data_preprocess_augmentation.py
    outs:
    - dataset/preprocess/train
    - dataset/preprocess/test
