base:
  random_seed: 42

data_split:
  test_size: 0.2


train:
  image_size: 224
  batch_size: 32
  fine_tune_args:
    epochs: 10
  letnet:
      base_lr: 0.01
  mini_vgg_net:
      base_lr: 0.01
  shallownet:
      base_lr: 0.01
evaluate:
  reports_dir: reports
  metrics_file: 'metrics.json'
  confusion_matrix_image: 'confusion_matrix.png'
  confusion_matrix_data: 'confusion_matrix_data.csv'


paths:
  dataset_url: https://www.kaggle.com/datasets/amansingh0000000/image-classification-and-yolo-dataset/data
  dataset_dir: dataset/raw
  dataset_path: dataset/image-classification-and-yolo-dataset/Ambulance_Car
  preprocess_dataset: dataset/preprocess
  train_dir: dataset/raw/image-classification-and-yolo-dataset/Ambulance_Car/Train
  labels_dir: dataset/raw/image-classification-and-yolo-dataset/Ambulance_Car/Label
  lenet_path: models/lenet.h5
  mini_vgg_net_path: models/mini_vgg_net.h5
  shallownet_path: models/shallownet.h5