base:
  random_seed: 42

data_split:
  test_size: 0.2

train:
  image_size: 224
  batch_size: 32
  binary_crossentropy: "binary_crossentropy"
  if_fine_tune: true
  fine_tune:
    models: ["lenet"] #, "mini_vgg_net", "shallownet"]
    base_lr: [0.01, 0.001, 0.0001]
    epochs: [10, 20, 30]
    optimizer: ["adam"] #, "sgd"]

  lenet:
    base_lr: 0.01
    epochs: 2
  mini_vgg_net:
    base_lr: 0.01
    epochs: 10
  shallownet:
    base_lr: 0.01
    epochs: 10

evaluate:
  metrics: ["accuracy", "precision", "recall"]
  reports_dir: reports
  metrics_file: "metrics.json"
  confusion_matrix_image: "confusion_matrix.png"
  confusion_matrix_data: "confusion_matrix_data.csv"

paths:
  dataset_url: https://www.kaggle.com/datasets/amansingh0000000/image-classification-and-yolo-dataset/data
  raw_dataset_dir: dataset/raw
  dataset_path: dataset/image-classification-and-yolo-dataset/Ambulance_Car
  preprocess_dataset: dataset/preprocess
  train_dir: dataset/raw/image-classification-and-yolo-dataset/Ambulance_Car/Train
  labels_dir: dataset/raw/image-classification-and-yolo-dataset/Ambulance_Car/Label
  preprocessed_train: /workspaces/car_vs_ambulance_classification_ensemble_cnn/dataset/preprocess/train
  preprocessed_val: /workspaces/car_vs_ambulance_classification_ensemble_cnn/dataset/preprocess/test
  lenet_path: models/lenet.h5
  mini_vgg_net_path: models/mini_vgg_net.h5
  shallownet_path: models/shallownet.h5
